# 3 Practice and Comprehensive Questions Solutions

In [62]:
# The following libraries are used, so please load them beforehand
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame
import os
import requests, zipfile
from io import StringIO
import io

# Visualization Library
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# Displayed to 3 decimal places
%precision 3

'%.3f'

In [64]:
# Specify the url with data
url = 'https://github.com/Hernan4444/MyAnimeList-Database/archive/refs/heads/master.zip'

# Acquire data from the url
r = requests.get(url, stream=True)

# read and extract the zipfile
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [65]:
!sudo apt-get install tree
!tree MyAnimeList-Database-master/

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tree is already the newest version (2.1.1-2ubuntu3.24.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
MyAnimeList-Database-master/
├── All Scrapping process.ipynb
├── data
│   ├── anime.csv
│   ├── animelist.csv
│   ├── anime_with_synopsis.csv
│   ├── html
│   │   ├── 1.zip
│   │   └── 5.zip
│   ├── rating_complete.csv
│   ├── readme.md
│   └── watching_status.csv
└── readme.md

3 directories, 10 files

In [66]:
anime_data = pd.read_csv('MyAnimeList-Database-master/data/anime.csv')
anime_list = pd.read_csv('MyAnimeList-Database-master/data/animelist.csv')
anime_synop = pd.read_csv('MyAnimeList-Database-master/data/anime_with_synopsis.csv')

cols_to_use = [
    'MAL_ID', 'Name', 'Score', 'Genres', 'Type', 'Aired', 'Studios', 'Source','Members'
]
anime_data_extracted = anime_data[cols_to_use]
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source,Members
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999",Sunrise,Original,1251960
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001",Bones,Original,273145
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga,558913
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002",Sunrise,Original,94683
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005",Toei Animation,Manga,13224

#### <Practice Question 3-1>

From `anime_data_extracted` that we just created, extract data where `Source` is `Manga` **and** `Members` is above 100000.

In [67]:
#　Condition filtering
anime_data_extracted = anime_data_extracted[anime_data_extracted['Score'] != 'Unknown']

anime_data_extracted[(anime_data_extracted['Source'] == 'Manga') & (anime_data_extracted['Members'] > 100000)].head()

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source,Members
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Madhouse,Manga,558913
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Gallop,Manga,148259
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",J.C.Staff,Manga,214499
8,18,Initial D Fourth Stage,8.15,"Action, Cars, Sports, Drama, Seinen",TV,"Apr 17, 2004 to Feb 18, 2006",A.C.G.T.,Manga,117929
9,19,Monster,8.76,"Drama, Horror, Mystery, Police, Psychological,...",TV,"Apr 7, 2004 to Sep 28, 2005",Madhouse,Manga,614100

#### <Practice Question 3-2>

Using only the `sort_values()` and `head()` functions, find the names of the 10 most recently added anime in this dataset.

Hint: Notice that `MAL_ID` values are larger for anime that were added recently, so sorting them by descending order will sort the anime from the most recent to the oldest.

In [68]:
anime_data_extracted.sort_values(by='MAL_ID',ascending=False).head(10)

,MAL_ID,Name,Score,Genres,Type,Aired,Studios,Source,Members
17552,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,"Mar 14, 2021",Bones,Original,10722
17513,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,"Feb 12, 2021",CloverWorks,Manga,13070
17512,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,"Feb 11, 2021",Unknown,Game,540
17505,47402,Heikousen,7.52,"Music, Romance",Music,"Feb 5, 2021","10Gauge, Studio DURIAN",Original,832
17504,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,"Feb 14, 2021",Unknown,Original,18161
17502,47307,Shin Gengou Nyankogelion,6.41,"Sci-Fi, Music, Mecha",Music,"Jan 22, 2021",PONOS Corporation,Original,472
17478,46491,Santa Company: Manatsu no Merry Christmas,5.68,Fantasy,Movie,"Jan 28, 2021",ORENDA,Original,1677
17469,46118,Wave!!: Surfing Yappe!! (TV),6.05,"Slice of Life, Sports",TV,"Jan 12, 2021 to ?",Asahi Production,Other,19952
17462,45999,Enen no Shouboutai Mini Anime,5.92,Comedy,ONA,"Jan 8, 2021 to ?",Unknown,Manga,5392
17459,45782,D4DJ Petit Mix,6.51,"Music, Comedy",TV,"Feb 5, 2021 to ?","W-Toon Studio, DMM.futureworks",Original,1575

#### <Practice Question  3-3>

Let's do an internal join between the following two data tables with the same `id` value.

In [69]:
# Prepare data 4
data4 = {
    'id':['0','1','2','3','4','6','8','11','12','13'],
    'city':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo','Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
    'birth_year':[1990,1989,1992,1997,1982,1991,1988,1990,1995,1981],
    'name':['Hiroshi','Akiko','Yuki','Satoru','Steeve','Mituru','Aoi','Tarou','Suguru','Mitsuo']
}
df4 = DataFrame(data4)
print(df4)

# Prepare data 5
data5 = {
    'id':['0','1','3','6','8'],
    'math':[20,30,50,70,90],
    'English':[30,50,50,70,20],
    'sex':['M','F','F','M','M'],
    'index_num':[0,1,2,3,4]
}
df5 = DataFrame(data5)
print(df5)

   id      city  birth_year     name
0   0     Tokyo        1990  Hiroshi
1   1     Osaka        1989    Akiko
2   2     Kyoto        1992     Yuki
3   3  Hokkaido        1997   Satoru
4   4     Tokyo        1982   Steeve
5   6     Tokyo        1991   Mituru
6   8     Osaka        1988      Aoi
7  11     Kyoto        1990    Tarou
8  12  Hokkaido        1995   Suguru
9  13     Tokyo        1981   Mitsuo
  id  math  English sex  index_num
0  0    20       30   M          0
1  1    30       50   F          1
2  3    50       50   F          2
3  6    70       70   M          3
4  8    90       20   M          4

In [70]:
# Answer
pd.merge(df4, df5, on='id')

  id      city  birth_year     name  math  English sex  index_num
0  0     Tokyo        1990  Hiroshi    20       30   M          0
1  1     Osaka        1989    Akiko    30       50   F          1
2  3  Hokkaido        1997   Satoru    50       50   F          2
3  6     Tokyo        1991   Mituru    70       70   M          3
4  8     Osaka        1988      Aoi    90       20   M          4

#### <Practice Question 3-4>
Using the data from <Exercise 3-3>, let's vertically join the following data for `df4`.

In [71]:
# Preparing data
data6 = {
    'id':['70','80','90','120','150'],
    'city':['Chiba','Kanagawa','Tokyo','Fukuoka','Okinawa'],
    'birth_year':[1980,1999,1995,1994,1994],
    'name':['Suguru','Kouichi','Satochi','Yukie','Akari']
}
df6 = DataFrame(data6)

In [72]:
pd.concat([df4, df6])

    id      city  birth_year     name
0    0     Tokyo        1990  Hiroshi
1    1     Osaka        1989    Akiko
2    2     Kyoto        1992     Yuki
3    3  Hokkaido        1997   Satoru
4    4     Tokyo        1982   Steeve
5    6     Tokyo        1991   Mituru
6    8     Osaka        1988      Aoi
7   11     Kyoto        1990    Tarou
8   12  Hokkaido        1995   Suguru
9   13     Tokyo        1981   Mitsuo
0   70     Chiba        1980   Suguru
1   80  Kanagawa        1999  Kouichi
2   90     Tokyo        1995  Satochi
3  120   Fukuoka        1994    Yukie
4  150   Okinawa        1994    Akari

In [73]:
hier_df1 = DataFrame(
    np.arange(12).reshape((3,4)),
    index = [['c','d','d'], [1,2,1]],
    columns = [
        ['Kyoto','Nagoya','Hokkaido','Kyoto'],
        ['Yellow','Yellow','Red','Blue']
    ]
)

hier_df1.index.names = ['key1','key2']
hier_df1.columns.names = ['city','color']
hier_df1

city       Kyoto Nagoya Hokkaido Kyoto
color     Yellow Yellow      Red  Blue
key1 key2
c    1         0      1        2     3
d    2         4      5        6     7
     1         8      9       10    11

#### <Practice Question 3-5>

Let's examine the relationship between `Score` and `Members` in the `anime_data_extracted` dataset.

(1) Group `Scores` into fixed rating ranges and save the result as `score_tiers`:
1. 0.0~6.0: 'Low'
2. 6.0~7.5: 'Average'
3. 7.5~8.5: 'High'
4. 8.5~10.0: 'Very High'

In [74]:
# Convert the Score column to type float first
anime_data_extracted["Score"] = anime_data_extracted["Score"].astype(float)

scores = [0.0,6.0,7.5,8.5,10.0]
score_tier_names = ['Low','Average','High','Very High']
score_tiers = pd.cut(anime_data_extracted["Score"], scores, labels=score_tier_names)

(2) Divide the member counts into 4 equal-sized popularity groups and save the result as `popularity_tiers`. Use the names 'Niche', 'Moderate', 'Popular', and 'Viral Hit' from lowest to highers.

In [75]:
popularity_tier_names = ['Niche','Moderate','Popular','Viral Hit']
popularity_tiers = pd.qcut(anime_data_extracted['Members'],4,labels=popularity_tier_names)

Run this code to display a 4 by 4 frequency grid showing how many anime fall into each score and popularity combination.

In [76]:
# Turns row categories into a full 2D table
pd.DataFrame({"Score": score_tiers, "Members": popularity_tiers}).value_counts().unstack()

Members     Niche  Moderate  Popular  Viral Hit
Score
Low        2000.0     941.0    352.0      100.0
Average    1108.0    2131.0   2446.0     1770.0
High          2.0      29.0    305.0     1134.0
Very High     NaN       NaN      2.0      101.0

#### <Practice Question 3-6>

Anime fans often joke that shows adapted from "Light Novels" have ridiculously long titles compared to original shows or manga. Let's see if this is true with `anime_data_extracted`. Group the dataset by `Source` and calculate the average (mean) `Title_Length` for each source type. Sort the results in descending order to see which source has the largest names.

In [77]:
# Creates a new column named 'Title_Length' that will store the length of each anime
anime_data_extracted['Title_Length'] = anime_data_extracted['Name'].str.len()

anime_data_extracted.groupby('Source')['Title_Length'].mean()

Source
4-koma manga     25.959839
Book             23.294118
Card game        28.116667
Digital manga    34.076923
Game             29.982069
Light novel      32.557123
Manga            25.845590
Music            17.157635
Novel            24.204489
Original         23.118391
Other            24.910543
Picture book     19.941176
Radio            34.166667
Unknown          27.155207
Visual novel     26.676230
Web manga        24.973684
Name: Title_Length, dtype: float64

#### <Practice Question 3-7>

Let's investigate the different animation studios. Group the `anime_data_extracted` dataset by `Studios`, then use the `agg()` function on the `Score` column to find the `mean`, `max`, and `count` for each studio.

In [78]:
anime_data_extracted.groupby('Studios')['Score'].agg(['mean','max','count'])

                                  mean   max  count
Studios
10Gauge                       6.490000  6.53      2
10Gauge, Studio DURIAN        7.520000  7.52      1
2:10 AM Animation             7.023333  7.25      3
8bit                          7.072683  8.07     41
A-1 Pictures                  7.138703  8.74    185
...                                ...   ...    ...
monofilmo                     7.335000  7.40      2
pH Studio                     6.260000  6.26      1
production doA                7.336667  7.79      3
ufotable                      7.248852  8.79     61
ufotable, feel., Studio Flag  6.910000  6.91      1

[948 rows x 3 columns]

#### <Practice Question 3-8>

We discussed many methods of handling missing data. Now let's observe how the choice of which method to use affects our analysis of the data. We are going to test these three methods on the `Score` column and see how it affects the mean value of `Score`.

1. Drop all rows with missing data
2. Fill all missing `Score` data with -1
3. Fill all missing `Score` data with the mean value of the `Score` data we have

Run this cell to turn all of the values in `Score` into `float` so we can calculate the mean.

In [79]:
anime_data = anime_data.replace('Unknown', np.nan)
cols_to_use2 = [
    "Name", "Score", "Type", "Premiered", "Studios", "Source",
]
anime_data_extracted_pracq = anime_data[cols_to_use2]
anime_data_extracted_pracq["Score"] = anime_data_extracted_pracq["Score"].astype(float)

/tmp/ipykernel_3197/2207846101.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_data_extracted_pracq["Score"] = anime_data_extracted_pracq["Score"].astype(float)

(1) Calculate the mean `Score` after removing all rows with at least one missing value.

In [80]:
anime_data_extracted_dropna = anime_data_extracted_pracq.dropna()
anime_data_extracted_dropna["Score"].mean()

np.float64(6.97429798578199)

(2) Calculate the mean `Score` after filling all missing values with -1.

In [81]:
anime_data_extracted_filln1 = anime_data_extracted_pracq.fillna(-1)
anime_data_extracted_filln1["Score"].mean()

np.float64(4.311564742056714)

(3) Calculate the mean `Score` after filling all missing `Score` values with the mean `Score` value for the data we currently have.

In [82]:
anime_data_extracted_fillmean = anime_data_extracted_pracq.fillna(anime_data_extracted_pracq["Score"].mean())
anime_data_extracted_fillmean["Score"].mean()

np.float64(6.509999194911843)

As we can see, the method we choose to handle the missing values greatly affects the mean `Score` value. There is never an absolute correct method to choose, and it is your job as a data scientist to balance the trade offs from both the data science side and the domain side and to choose the method that makes the most sense.

## 3.7 Comprehensive Question

### Comprehensive Question 3-1 Data Manipulation

Using the data `student-mat.csv', which is the data showing math scores, answer the following questions.

(1) For the above data, calculate the average score of `G1` by age (`age`) x sex (`sex`) and create a table (table) such that the vertical axis is age (`age`) and the horizontal axis is sex (`sex`).

(2) For the result table displayed in (1), delete all the rows (records) that are NaN.

In [83]:
# Specify the url with data
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip'

# Acquire data from the url
r = requests.get(url, stream=True)

# read and extract the zipfile
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

# Load the data
student_data_math = pd.read_csv('student-mat.csv', sep=';')

In [84]:
# Answer
# (1)
student_data_math.groupby(['age','sex'])['G1'].mean().unstack()

sex          F          M
age
15   10.052632  12.250000
16   10.203704  11.740000
17   11.103448  10.600000
18   10.883721  10.538462
19   10.642857   9.700000
20   15.000000  13.000000
21         NaN  10.000000
22         NaN   6.000000

In [85]:
# Answer
# (2)
student_data_math.groupby(['age','sex'])['G1'].mean().unstack().dropna()

sex          F          M
age
15   10.052632  12.250000
16   10.203704  11.740000
17   11.103448  10.600000
18   10.883721  10.538462
19   10.642857   9.700000
20   15.000000  13.000000

# How to Load Data

In [86]:
# Specify url with data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip'
# Specify data from url
r = requests.get(url, stream=True)
# Extract student-mat.csv in the zipfile to the data directory in the current directory
with zipfile.ZipFile(io.BytesIO(r.content)) as existing_zip:
    existing_zip.extract('student-mat.csv', 'data')
# Directory where csvfile exists
data_dir = './data'
path = os.path.join(data_dir, 'student-mat.csv')
student_data_math = pd.read_csv(path,sep=';')



---

**Acknowledgement**: For the usage of dataset below
https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

**References**: Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [[http://archive.ics.uci.edu/ml](http://archive.ics.uci.edu/ml)]. Irvine, CA: University of California, School of Information and Computer Science.

P. Cortez and A. Silva. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp.5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7.
[http://www3.dsi.uminho.pt/pcortez/student.pdf](http://www3.dsi.uminho.pt/pcortez/student.pdf)